name: home
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  forexample:
    path: ../../../forexample
  login:
    path: ../login_module
  profile_module:
    path: ../profile_module

  freezed_annotation: ^2.0.3
  flutter_bloc: ^8.0.1
  beamer: ^1.4.1+1
  artemis: ^7.8.0-beta
  easy_localization: ^3.0.1
  bloc_concurrency: ^0.2.0
  bloc_test: ^9.0.3
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
