name: profile_module
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  widgets:
    path: ../widgets

  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  shared_preferences: ^2.0.15
  easy_localization: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11

flutter:
